# See: https://taskfile.dev/docs/

version: "3"

tasks:
  run-app:
    aliases:
      - run
    desc: "Run application"
    vars:
      CONFIG_PATH: '{{default "./configs/local.yaml" .CONFIG_PATH}}'
    env:
      CONFIG_PATH: "{{.CONFIG_PATH}}"
    cmds:
      - go run cmd/app/main.go

  migrate-up:
    desc: "Up database migrations"
    vars:
      CONFIG_PATH: '{{default "./configs/local.yaml" .CONFIG_PATH}}'
    env:
      CONFIG_PATH: "{{.CONFIG_PATH}}"
    cmds:
      - go run cmd/migrator/main.go up

  migrate-down:
    desc: "Down database migrations"
    vars:
      CONFIG_PATH: '{{default "./configs/local.yaml" .CONFIG_PATH}}'
    env:
      CONFIG_PATH: "{{.CONFIG_PATH}}"
    cmds:
      - go run cmd/migrator/main.go down

  integration-test:
    desc: "Run integration tests"
    vars:
      CONFIG_PATH: '{{default "../configs/int_tests.yaml" .CONFIG_PATH}}'
    env:
      CONFIG_PATH: "{{.CONFIG_PATH}}"
    cmds:
      - docker compose -f ./docker/tests/docker-compose.yml up -d
      - sleep 5
      - go test -v -tags=integration ./tests/...