// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domains "github.com/Deymos01/pr-review-manager/internal/domains"
	mock "github.com/stretchr/testify/mock"
)

// TeamRepository is an autogenerated mock type for the TeamRepository type
type TeamRepository struct {
	mock.Mock
}

// CreateTeam provides a mock function with given fields: ctx, _a1
func (_m *TeamRepository) CreateTeam(ctx context.Context, _a1 *domains.Team) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domains.Team) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTeamByName provides a mock function with given fields: ctx, name
func (_m *TeamRepository) GetTeamByName(ctx context.Context, name string) (*domains.Team, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamByName")
	}

	var r0 *domains.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domains.Team, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domains.Team); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamExists provides a mock function with given fields: ctx, name
func (_m *TeamRepository) TeamExists(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for TeamExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTeamRepository creates a new instance of TeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamRepository {
	mock := &TeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
