// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domains "github.com/Deymos01/pr-review-manager/internal/domains"

	mock "github.com/stretchr/testify/mock"
)

// PRService is an autogenerated mock type for the PRService type
type PRService struct {
	mock.Mock
}

// MergePullRequest provides a mock function with given fields: ctx, prID
func (_m *PRService) MergePullRequest(ctx context.Context, prID string) (*domains.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for MergePullRequest")
	}

	var r0 *domains.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domains.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domains.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPRService creates a new instance of PRService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRService {
	mock := &PRService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
