// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domains "github.com/Deymos01/pr-review-manager/internal/domains"
	mock "github.com/stretchr/testify/mock"
)

// PRService is an autogenerated mock type for the PRService type
type PRService struct {
	mock.Mock
}

// ReassignReviewer provides a mock function with given fields: ctx, prID, oldUserID
func (_m *PRService) ReassignReviewer(ctx context.Context, prID string, oldUserID string) (*domains.PullRequest, string, error) {
	ret := _m.Called(ctx, prID, oldUserID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 *domains.PullRequest
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domains.PullRequest, string, error)); ok {
		return rf(ctx, prID, oldUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domains.PullRequest); ok {
		r0 = rf(ctx, prID, oldUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, prID, oldUserID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, prID, oldUserID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewPRService creates a new instance of PRService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRService {
	mock := &PRService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
