// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domains "github.com/Deymos01/pr-review-manager/internal/domains"
	mock "github.com/stretchr/testify/mock"
)

// PullRequestRepository is an autogenerated mock type for the PullRequestRepository type
type PullRequestRepository struct {
	mock.Mock
}

// CreatePullRequest provides a mock function with given fields: ctx, prID, prName, authorID
func (_m *PullRequestRepository) CreatePullRequest(ctx context.Context, prID string, prName string, authorID string) ([]string, error) {
	ret := _m.Called(ctx, prID, prName, authorID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]string, error)); ok {
		return rf(ctx, prID, prName, authorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []string); ok {
		r0 = rf(ctx, prID, prName, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, prID, prName, authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPullRequestByID provides a mock function with given fields: ctx, prID
func (_m *PullRequestRepository) GetPullRequestByID(ctx context.Context, prID string) (*domains.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestByID")
	}

	var r0 *domains.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domains.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domains.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergePullRequest provides a mock function with given fields: ctx, prID
func (_m *PullRequestRepository) MergePullRequest(ctx context.Context, prID string) error {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for MergePullRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PullRequestExists provides a mock function with given fields: ctx, prID
func (_m *PullRequestRepository) PullRequestExists(ctx context.Context, prID string) (bool, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for PullRequestExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestMerged provides a mock function with given fields: ctx, prID
func (_m *PullRequestRepository) PullRequestMerged(ctx context.Context, prID string) (bool, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for PullRequestMerged")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, prID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReassignReviewer provides a mock function with given fields: ctx, prID, oldUserID
func (_m *PullRequestRepository) ReassignReviewer(ctx context.Context, prID string, oldUserID string) (string, error) {
	ret := _m.Called(ctx, prID, oldUserID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignReviewer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, prID, oldUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, prID, oldUserID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, prID, oldUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPullRequestRepository creates a new instance of PullRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestRepository {
	mock := &PullRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
